### ISSUE TITLE
ther is already a moreitems mod on tthunderstore 

### ISSUE THREAD

**Issue by benjdidj** [CarlHalstead/Risk-of-Rain-2-More-Items#1]
there is already a moreitems mod on tthunderstore :
https://thunderstore.io/package/XoXFaby/MoreItems/1.1.4/

it is confusing. thx anyway.

**Comment by CarlHalstead** [comment]
Thanks for the comment. I did notice that other mod, I chose to not worry about the name however as it is still in development and will evolve over time. To reduce confusion the name will definitely have to change at some point however it is not my highest priority at present. I am sure you understand. Many thanks!
